// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiLog struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	ProjectID    pgtype.Text        `json:"project_id"`
	Type         string             `json:"type"`
	Prompt       pgtype.Text        `json:"prompt"`
	Result       pgtype.Text        `json:"result"`
	CostPoints   int32              `json:"cost_points"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	Title        string             `json:"title"`
	NovelTitle   pgtype.Text        `json:"novel_title"`
	SourceText   string             `json:"source_text"`
	ConfigJson   string             `json:"config_json"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Scene struct {
	ID        string             `json:"id"`
	ProjectID string             `json:"project_id"`
	SceneNo   int32              `json:"scene_no"`
	Title     string             `json:"title"`
	Location  pgtype.Text        `json:"location"`
	TimeText  pgtype.Text        `json:"time_text"`
	Summary   pgtype.Text        `json:"summary"`
	Content   string             `json:"content"`
	RawJson   pgtype.Text        `json:"raw_json"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Nickname     string             `json:"nickname"`
	AiPoints     int32              `json:"ai_points"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
