// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT count(*)::int
FROM projects
WHERE user_id = $1
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%' OR COALESCE(novel_title, '') ILIKE '%' || $2 || '%')
`

type CountProjectsParams struct {
	UserID  string `json:"user_id"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countProjects, arg.UserID, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, user_id, title, novel_title, source_text, config_json, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 'draft', now(), now())
RETURNING id, user_id, title, novel_title, source_text, config_json, status, error_message, created_at, updated_at
`

type CreateProjectParams struct {
	ID         string      `json:"id"`
	UserID     string      `json:"user_id"`
	Title      string      `json:"title"`
	NovelTitle pgtype.Text `json:"novel_title"`
	SourceText string      `json:"source_text"`
	ConfigJson string      `json:"config_json"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.NovelTitle,
		arg.SourceText,
		arg.ConfigJson,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.NovelTitle,
		&i.SourceText,
		&i.ConfigJson,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects
WHERE id = $1 AND user_id = $2
`

type DeleteProjectParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectByIDForUser = `-- name: GetProjectByIDForUser :one
SELECT id, user_id, title, novel_title, source_text, config_json, status, error_message, created_at, updated_at
FROM projects
WHERE id = $1 AND user_id = $2
`

type GetProjectByIDForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetProjectByIDForUser(ctx context.Context, arg GetProjectByIDForUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDForUser, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.NovelTitle,
		&i.SourceText,
		&i.ConfigJson,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.user_id, p.title, p.novel_title, p.source_text, p.config_json, p.status, p.error_message, p.created_at, p.updated_at,
       count(s.id)::int AS scene_count
FROM projects p
LEFT JOIN scenes s ON s.project_id = p.id
WHERE p.user_id = $1
  AND ($2::text = '' OR p.title ILIKE '%' || $2 || '%' OR COALESCE(p.novel_title, '') ILIKE '%' || $2 || '%')
GROUP BY p.id
ORDER BY p.updated_at DESC
LIMIT $3 OFFSET $4
`

type ListProjectsParams struct {
	UserID  string `json:"user_id"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListProjectsRow struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	Title        string             `json:"title"`
	NovelTitle   pgtype.Text        `json:"novel_title"`
	SourceText   string             `json:"source_text"`
	ConfigJson   string             `json:"config_json"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	SceneCount   int32              `json:"scene_count"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.NovelTitle,
			&i.SourceText,
			&i.ConfigJson,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SceneCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectInfo = `-- name: UpdateProjectInfo :one
UPDATE projects
SET title = $3, novel_title = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, novel_title, source_text, config_json, status, error_message, created_at, updated_at
`

type UpdateProjectInfoParams struct {
	ID         string      `json:"id"`
	UserID     string      `json:"user_id"`
	Title      string      `json:"title"`
	NovelTitle pgtype.Text `json:"novel_title"`
}

func (q *Queries) UpdateProjectInfo(ctx context.Context, arg UpdateProjectInfoParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectInfo,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.NovelTitle,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.NovelTitle,
		&i.SourceText,
		&i.ConfigJson,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectStatus = `-- name: UpdateProjectStatus :one
UPDATE projects
SET status = $3, error_message = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, novel_title, source_text, config_json, status, error_message, created_at, updated_at
`

type UpdateProjectStatusParams struct {
	ID           string      `json:"id"`
	UserID       string      `json:"user_id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectStatus,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.ErrorMessage,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.NovelTitle,
		&i.SourceText,
		&i.ConfigJson,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
