// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scenes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScene = `-- name: CreateScene :one
INSERT INTO scenes (id, project_id, scene_no, title, location, time_text, summary, content, raw_json, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now())
RETURNING id, project_id, scene_no, title, location, time_text, summary, content, raw_json, created_at, updated_at
`

type CreateSceneParams struct {
	ID        string      `json:"id"`
	ProjectID string      `json:"project_id"`
	SceneNo   int32       `json:"scene_no"`
	Title     string      `json:"title"`
	Location  pgtype.Text `json:"location"`
	TimeText  pgtype.Text `json:"time_text"`
	Summary   pgtype.Text `json:"summary"`
	Content   string      `json:"content"`
	RawJson   pgtype.Text `json:"raw_json"`
}

func (q *Queries) CreateScene(ctx context.Context, arg CreateSceneParams) (Scene, error) {
	row := q.db.QueryRow(ctx, createScene,
		arg.ID,
		arg.ProjectID,
		arg.SceneNo,
		arg.Title,
		arg.Location,
		arg.TimeText,
		arg.Summary,
		arg.Content,
		arg.RawJson,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SceneNo,
		&i.Title,
		&i.Location,
		&i.TimeText,
		&i.Summary,
		&i.Content,
		&i.RawJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScenesByProjectID = `-- name: DeleteScenesByProjectID :exec
DELETE FROM scenes
WHERE project_id = $1
`

func (q *Queries) DeleteScenesByProjectID(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, deleteScenesByProjectID, projectID)
	return err
}

const getSceneForUser = `-- name: GetSceneForUser :one
SELECT s.id, s.project_id, s.scene_no, s.title, s.location, s.time_text, s.summary, s.content, s.raw_json, s.created_at, s.updated_at
FROM scenes s
JOIN projects p ON p.id = s.project_id
WHERE s.id = $1 AND p.user_id = $2
`

type GetSceneForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetSceneForUser(ctx context.Context, arg GetSceneForUserParams) (Scene, error) {
	row := q.db.QueryRow(ctx, getSceneForUser, arg.ID, arg.UserID)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SceneNo,
		&i.Title,
		&i.Location,
		&i.TimeText,
		&i.Summary,
		&i.Content,
		&i.RawJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScenesForUserProject = `-- name: ListScenesForUserProject :many
SELECT s.id, s.project_id, s.scene_no, s.title, s.location, s.time_text, s.summary, s.content, s.raw_json, s.created_at, s.updated_at
FROM scenes s
JOIN projects p ON p.id = s.project_id
WHERE s.project_id = $1 AND p.user_id = $2
ORDER BY s.scene_no ASC
`

type ListScenesForUserProjectParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ListScenesForUserProject(ctx context.Context, arg ListScenesForUserProjectParams) ([]Scene, error) {
	rows, err := q.db.Query(ctx, listScenesForUserProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scene
	for rows.Next() {
		var i Scene
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SceneNo,
			&i.Title,
			&i.Location,
			&i.TimeText,
			&i.Summary,
			&i.Content,
			&i.RawJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSceneForUser = `-- name: UpdateSceneForUser :one
UPDATE scenes s
SET title = $3,
    location = $4,
    time_text = $5,
    summary = $6,
    content = $7,
    updated_at = now()
FROM projects p
WHERE s.id = $1 AND s.project_id = p.id AND p.user_id = $2
RETURNING s.id, s.project_id, s.scene_no, s.title, s.location, s.time_text, s.summary, s.content, s.raw_json, s.created_at, s.updated_at
`

type UpdateSceneForUserParams struct {
	ID       string      `json:"id"`
	UserID   string      `json:"user_id"`
	Title    string      `json:"title"`
	Location pgtype.Text `json:"location"`
	TimeText pgtype.Text `json:"time_text"`
	Summary  pgtype.Text `json:"summary"`
	Content  string      `json:"content"`
}

func (q *Queries) UpdateSceneForUser(ctx context.Context, arg UpdateSceneForUserParams) (Scene, error) {
	row := q.db.QueryRow(ctx, updateSceneForUser,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Location,
		arg.TimeText,
		arg.Summary,
		arg.Content,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SceneNo,
		&i.Title,
		&i.Location,
		&i.TimeText,
		&i.Summary,
		&i.Content,
		&i.RawJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
