// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, nickname, ai_points, created_at, updated_at)
VALUES ($1, $2, $3, $4, 1000, now(), now())
RETURNING id, email, password_hash, nickname, ai_points, created_at, updated_at
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Nickname     string `json:"nickname"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Nickname,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.AiPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementUserAIPoints = `-- name: DecrementUserAIPoints :one
UPDATE users
SET ai_points = ai_points - $2, updated_at = now()
WHERE id = $1 AND ai_points >= $2
RETURNING id, email, password_hash, nickname, ai_points, created_at, updated_at
`

type DecrementUserAIPointsParams struct {
	ID       string `json:"id"`
	AiPoints int32  `json:"ai_points"`
}

func (q *Queries) DecrementUserAIPoints(ctx context.Context, arg DecrementUserAIPointsParams) (User, error) {
	row := q.db.QueryRow(ctx, decrementUserAIPoints, arg.ID, arg.AiPoints)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.AiPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, nickname, ai_points, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.AiPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, nickname, ai_points, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.AiPoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
